
#GTEST=/home/kusiu/libs
#INCLUDE= -I $(GTEST)/googlemock/include -I $(GTEST)/googletest/include
#LIB= -L $(GTEST)/lib

all :
	g++ -std=c++11 thread.cpp -o thread.x -pthread

clean:
	rm test

#	g++ test.cpp -o test -I /home/kusiu/libs/googlemock/include -I /home/kusiu/libs/googletest/include/ -L /home/kusiu/libs/lib/ -lgmock -lgmock_main -pthread
