
GTEST=/home/kusiu/libs

INCLUDE= -I $(GTEST)/googlemock/include -I $(GTEST)/googletest/include
LIB= -L $(GTEST)/lib

all :
	g++ test.cpp -o test $(INCLUDE) $(LIB) -lgmock -lgmock_main -pthread



#	g++ test.cpp -o test -I /home/kusiu/libs/googlemock/include -I /home/kusiu/libs/googletest/include/ -L /home/kusiu/libs/lib/ -lgmock -lgmock_main -pthread
